services:
  postgres:
    image: postgres:16
    container_name: careflow-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: careflow

    ports:
      - "5432:5432"

    volumes:
      - careflow-postgres-data:/var/lib/postgresql/data

volumes:
  careflow-postgres-data: